// <auto-generated />
using System;
using CityInfoNew.Repositories.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CityInfoNew.Repositories.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260915154344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CityInfoNew.Entities.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Famous for its historic imperial cathedral and thermal springs.",
                            Name = "Aachen"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Renowned for its gothic town hall and fairytale folklore.",
                            Name = "Bremen"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Home to the massive twin-spired Cologne Cathedral.",
                            Name = "Cologne"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The vibrant capital, known for the Brandenburg Gate and rich modern history.",
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Celebrated for its restored baroque architecture like the Frauenkirche.",
                            Name = "Dresden"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Known for its futuristic skyscraper skyline mixed with a reconstructed old town.",
                            Name = "Frankfurt am Main"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A major northern port city with scenic canals and maritime charm.",
                            Name = "Hamburg"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Famous for its romantic castle ruins and historic university.",
                            Name = "Heidelberg"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The Bavarian capital famous for beer gardens and royal palaces.",
                            Name = "Munich"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Known for its medieval castle and famous Christmas market.",
                            Name = "Nuremberg"
                        });
                });

            modelBuilder.Entity("CityInfoNew.Entities.Models.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "One of the oldest cathedrals in Europe and the burial place of Charlemagne.",
                            Name = "Aachen Cathedral"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "A neoclassical pavilion symbolising Aachen's spa and bathing culture.",
                            Name = "Elisenbrunnen"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Description = "The historic city hall built on the ruins of Charlemagne's palace.",
                            Name = "Aachen Rathaus"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "A UNESCO World Heritage site and a brilliant example of Weser Renaissance architecture.",
                            Name = "Bremen Town Hall"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Description = "The famous bronze statue based on the Brothers Grimm fairytale.",
                            Name = "Town Musicians Statue"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            Description = "Bremen's oldest neighborhood with narrow winding streets and tiny houses.",
                            Name = "Schnoor Quarter"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 3,
                            Description = "A massive Gothic cathedral with twin spires towering over the city.",
                            Name = "Cologne Cathedral"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 3,
                            Description = "Houses one of the most important collections of modern art in Europe.",
                            Name = "Museum Ludwig"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 3,
                            Description = "Famous for its thousands of love locks and great views of the cathedral.",
                            Name = "Hohenzollern Bridge"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 4,
                            Description = "An 18th-century neoclassical monument and one of Germany's most famous landmarks.",
                            Name = "Brandenburg Gate"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 4,
                            Description = "The historic building in Berlin which houses the German parliament (Bundestag).",
                            Name = "Reichstag Building"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 4,
                            Description = "A UNESCO World Heritage site featuring five world-class museums.",
                            Name = "Museum Island"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 5,
                            Description = "A stunning baroque church reconstructed after World War II.",
                            Name = "Frauenkirche"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 5,
                            Description = "A palatial complex with gardens, serving as an excellent example of Baroque architecture.",
                            Name = "Zwinger Palace"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 5,
                            Description = "The magnificent opera house of the Sächsische Staatsoper Dresden.",
                            Name = "Semperoper"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 6,
                            Description = "The historic heart of Frankfurt featuring traditional half-timbered houses.",
                            Name = "Römerberg"
                        },
                        new
                        {
                            Id = 17,
                            CityId = 6,
                            Description = "A prominent skyscraper offering a public viewing observatory of the city skyline.",
                            Name = "Main Tower"
                        },
                        new
                        {
                            Id = 18,
                            CityId = 6,
                            Description = "One of three botanical gardens in Frankfurt, featuring diverse global flora.",
                            Name = "Palmengarten"
                        },
                        new
                        {
                            Id = 19,
                            CityId = 7,
                            Description = "The largest warehouse district in the world where buildings stand on timber-pile foundations.",
                            Name = "Speicherstadt"
                        },
                        new
                        {
                            Id = 20,
                            CityId = 7,
                            Description = "A striking modern concert hall located in the HafenCity quarter.",
                            Name = "Elbphilharmonie"
                        },
                        new
                        {
                            Id = 21,
                            CityId = 7,
                            Description = "The world's largest model railway exhibition.",
                            Name = "Miniatur Wunderland"
                        },
                        new
                        {
                            Id = 22,
                            CityId = 8,
                            Description = "The iconic red sandstone ruins towering above the old town.",
                            Name = "Heidelberg Castle"
                        },
                        new
                        {
                            Id = 23,
                            CityId = 8,
                            Description = "The beautiful old stone bridge crossing the Neckar river.",
                            Name = "Alte Brücke"
                        },
                        new
                        {
                            Id = 24,
                            CityId = 9,
                            Description = "The central square in the city centre of Munich, featuring the famous Glockenspiel.",
                            Name = "Marienplatz"
                        },
                        new
                        {
                            Id = 25,
                            CityId = 9,
                            Description = "A Baroque palace that was the main summer residence of the former rulers of Bavaria.",
                            Name = "Nymphenburg Palace"
                        },
                        new
                        {
                            Id = 26,
                            CityId = 9,
                            Description = "A large public park, one of the world's largest urban public parks.",
                            Name = "Englischer Garten"
                        },
                        new
                        {
                            Id = 27,
                            CityId = 10,
                            Description = "A group of medieval fortified buildings on a sandstone ridge dominating the historical center.",
                            Name = "Nuremberg Castle"
                        },
                        new
                        {
                            Id = 28,
                            CityId = 10,
                            Description = "The central square, famous for the Schöner Brunnen and the annual Christmas market.",
                            Name = "Hauptmarkt"
                        });
                });

            modelBuilder.Entity("CityInfoNew.Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CityInfoNew.Entities.Models.PointOfInterest", b =>
                {
                    b.HasOne("CityInfoNew.Entities.Models.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfoNew.Entities.Models.User", b =>
                {
                    b.HasOne("CityInfoNew.Entities.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CityInfoNew.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CityInfoNew.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityInfoNew.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CityInfoNew.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CityInfoNew.Entities.Models.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
